version: "3"
services:
    srp-exporter:
        image: srp-exporter:latest
        ports: 
            - "8000:8000"
        env_file: 
            - .env
    prometheus:
        image: prom/prometheus:v2.28.1
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana:8.0.6-ubuntu
        ports:
            - "3000:3000"
        volumes:
            - ./grafana/grafana.ini:/etc/grafana/grafana.ini
            - ./grafana/provisioning:/etc/grafana/provisioning

