{
 "title": "SRP Energy",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Yesterday's Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_usage" }
   ]
  },
  {
   "title": "Yesterday's Cost",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_cost" }
   ]
  },
  {
   "title": "Energy Usage (kwh) per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "energy_usage{job=\"srp\"}"
    }
   ]
  },
  {
   "title": "Energy Cost ($) per day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "energy_cost{job=\"srp\"}"
    }
   ]
  }
 ]
}